apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/capz-serving-cert'
    controller-gen.kubebuilder.io/version: v0.18.0
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cluster-api-provider-azure
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    application.giantswarm.io/team: '{{ index .Chart.Annotations "application.giantswarm.io/team" }}'
    cluster.x-k8s.io/provider: infrastructure-azure
    cluster.x-k8s.io/v1beta1: v1beta1
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/move: ""
    helm.sh/chart: cluster-api-provider-azure
  name: azureasomanagedcontrolplanetemplates.infrastructure.cluster.x-k8s.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: capz-webhook-service
          namespace: '{{ .Release.Namespace }}'
          path: /convert
          port: 443
      conversionReviewVersions:
        - v1
        - v1beta1
  group: infrastructure.cluster.x-k8s.io
  names:
    kind: AzureASOManagedControlPlaneTemplate
    listKind: AzureASOManagedControlPlaneTemplateList
    plural: azureasomanagedcontrolplanetemplates
    singular: azureasomanagedcontrolplanetemplate
  scope: Namespaced
  versions:
    - deprecated: true
      deprecationWarning: infrastructure.cluster.x-k8s.io/v1alpha1 AzureASOManagedControlPlaneTemplate is deprecated. infrastructure.cluster.x-k8s.io/v1beta1 is equivalent and should be used instead.
      name: v1alpha1
      schema: {}
      served: true
      storage: false
    - name: v1beta1
      schema: {}
      served: true
      storage: true
